// Auto-generated from category pages — Phase A of pSEO migration
// Maps each category slug to its visual assets for the pSEO template

export interface ExploreCard { href: string; label: string; sub: string; icon: string; }

export interface CategoryAssets {
  heroImage: string;
  bgColor: string;
  bentoSectionLabel: string;
  bentoImages: string[];
  bentoIcons: string[];
  exploreCards: ExploreCard[];
}

export const CATEGORY_ASSET_REGISTRY: Record<string, CategoryAssets> = {
  'remote': {
    heroImage: '/images/categories/hero_wc_remote.png',
    bgColor: '#e8af9b',
    bentoSectionLabel: 'Why Go Remote',
    bentoImages: [
      '/images/categories/bento_remote_office.png',
      '/images/categories/bento_multi_state_impact.png',
      '/images/categories/bento_salary_growth.png',
    ],
    bentoIcons: [
      '/images/categories/icon_remote_flex.png',
      '/images/categories/icon_remote_home.png',
      '/images/categories/icon_remote_reach.png',
    ],
    exploreCards: [
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual patient care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/travel', label: 'Travel', sub: 'Locum tenens', icon: '/images/categories/clay_icon_travel.png' },
      { href: '/jobs/new-grad', label: 'New Grad', sub: 'Entry-level roles', icon: '/images/categories/clay_icon_newgrad.png' },
      { href: '/jobs/per-diem', label: 'Per Diem', sub: 'Flexible shifts', icon: '/images/categories/clay_icon_perdiem.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'telehealth': {
    heroImage: '/images/categories/hero_wc_th_people.png',
    bgColor: '#f1d49c',
    bentoSectionLabel: 'Why Choose Telehealth',
    bentoImages: [
      '/images/categories/bento_th_videocall.png',
      '/images/categories/bento_th_multistate.png',
      '/images/categories/bento_th_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_telehealth_laptop.png',
      '/images/categories/icon_telehealth_home.png',
      '/images/categories/icon_telehealth_reach.png',
      '/images/categories/icon_telehealth_flex.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/substance-abuse', label: 'Substance Abuse', sub: 'Addiction care', icon: '/images/categories/clay_icon_substance.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'inpatient': {
    heroImage: '/images/categories/hero_v3_inpatient.png',
    bgColor: '#a0b7c4',
    bentoSectionLabel: 'Why Choose Inpatient',
    bentoImages: [
      '/images/categories/bento_inp_ward.png',
      '/images/categories/bento_inp_comp.png',
      '/images/categories/bento_inpatient_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_inp_pay.png',
      '/images/categories/icon_inp_structured.png',
      '/images/categories/icon_inp_schedule.png',
    ],
    exploreCards: [
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based care', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/crisis', label: 'Crisis', sub: 'Emergency psych', icon: '/images/categories/clay_icon_crisis.png' },
      { href: '/jobs/correctional', label: 'Correctional', sub: 'Forensic settings', icon: '/images/categories/clay_icon_correctional.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'outpatient': {
    heroImage: '/images/categories/hero_v2_outpatient.png',
    bgColor: '#9ed2ba',
    bentoSectionLabel: 'Why Choose Outpatient',
    bentoImages: [
      '/images/categories/bento_outpatient_clinic.png',
      '/images/categories/bento_outpatient_panel.png',
      '/images/categories/bento_outpatient_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_outpatient_clinic.png',
      '/images/categories/icon_outpatient_clock.png',
      '/images/categories/icon_outpatient_therapy.png',
      '/images/categories/icon_outpatient_growth.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/community-health', label: 'Community Health', sub: 'FQHC & public', icon: '/images/categories/clay_icon_communityhealth.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'travel': {
    heroImage: '/images/categories/hero_wc_travel.png',
    bgColor: '#81c1da',
    bentoSectionLabel: 'Why Choose Travel',
    bentoImages: [
      '/images/categories/bento_travel_adventure.png',
      '/images/categories/bento_travel_housing.png',
      '/images/categories/bento_travel_compensation.png',
    ],
    bentoIcons: [
      '/images/categories/icon_travel_case.png',
      '/images/categories/icon_travel_plane.png',
      '/images/categories/icon_travel_housing.png',
      '/images/categories/icon_travel_dollar.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/locum-tenens', label: 'Locum Tenens', sub: 'Short-term fills', icon: '/images/categories/clay_icon_locumtenens.png' },
      { href: '/jobs/contract', label: 'Contract', sub: 'Fixed-term roles', icon: '/images/categories/clay_icon_contract.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'addiction': {
    heroImage: '/images/categories/hero_v2_addiction.png',
    bgColor: '#aabe9c',
    bentoSectionLabel: 'Why Choose Addiction & SUD',
    bentoImages: [
      '/images/categories/bento_addiction_recovery.png',
      '/images/categories/bento_addiction_mat.png',
      '/images/categories/bento_addiction_impact.png',
    ],
    bentoIcons: [
      '/images/categories/icon_addiction_demand.png',
      '/images/categories/icon_addiction_dual.png',
      '/images/categories/icon_addiction_heart.png',
      '/images/categories/icon_addiction_harm.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'child-adolescent': {
    heroImage: '/images/categories/hero_wc_childadolescent.png',
    bgColor: '#e3ac73',
    bentoSectionLabel: 'Why Choose Child & Adolescent',
    bentoImages: [
      '/images/categories/bento_child_clinic.png',
      '/images/categories/bento_child_school.png',
      '/images/categories/bento_child_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_child_teddy.png',
      '/images/categories/icon_child_school.png',
      '/images/categories/icon_child_family.png',
      '/images/categories/icon_child_play.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'substance-abuse': {
    heroImage: '/images/categories/hero_wc_sa_people.png',
    bgColor: '#9bb7a5',
    bentoSectionLabel: 'Why Choose Substance Abuse',
    bentoImages: [
      '/images/categories/bento_sa_counseling.png',
      '/images/categories/bento_sa_grouptherapy.png',
      '/images/categories/bento_sa_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_sa_recovery.png',
      '/images/categories/icon_sa_medicine.png',
      '/images/categories/icon_sa_group.png',
      '/images/categories/icon_sa_impact.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'new-grad': {
    heroImage: '/images/categories/hero_wc_newgrad.png',
    bgColor: '#99a7d4',
    bentoSectionLabel: 'Why Choose New Grad',
    bentoImages: [
      '/images/categories/bento_newgrad_mentorship.png',
      '/images/categories/bento_newgrad_career.png',
      '/images/categories/bento_newgrad_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_newgrad_diploma.png',
      '/images/categories/icon_newgrad_bulb.png',
      '/images/categories/icon_newgrad_stairs.png',
      '/images/categories/icon_newgrad_cert.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'per-diem': {
    heroImage: '/images/categories/hero_v2_perdiem.png',
    bgColor: '#dcba74',
    bentoSectionLabel: 'Why Choose Per Diem',
    bentoImages: [
      '/images/categories/bento_pd_shifts.png',
      '/images/categories/bento_pd_free.png',
      '/images/categories/bento_pd_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_perdiem_shift.png',
      '/images/categories/icon_perdiem_wallet.png',
      '/images/categories/icon_perdiem_nosign.png',
      '/images/categories/icon_perdiem_variety.png',
    ],
    exploreCards: [
      { href: '/jobs/part-time', label: 'Part-Time', sub: 'Flexible hours', icon: '/images/categories/clay_icon_parttime.png' },
      { href: '/jobs/contract', label: 'Contract', sub: 'Fixed-term roles', icon: '/images/categories/clay_icon_contract.png' },
      { href: '/jobs/locum-tenens', label: 'Locum Tenens', sub: 'Travel assignments', icon: '/images/categories/clay_icon_locumtenens.png' },
      { href: '/jobs/full-time', label: 'Full-Time', sub: 'Standard schedules', icon: '/images/categories/clay_icon_fulltime.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'full-time': {
    heroImage: '/images/categories/hero_wc_fulltime.png',
    bgColor: '#88a7c4',
    bentoSectionLabel: 'Why Choose Full-Time',
    bentoImages: [
      '/images/categories/bento_ft_benefits.png',
      '/images/categories/bento_ft_stability.png',
      '/images/categories/bento_ft_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_ft_benefits.png',
      '/images/categories/icon_ft_security.png',
      '/images/categories/icon_ft_team.png',
      '/images/categories/icon_ft_balance.png',
    ],
    exploreCards: [
      { href: '/jobs/part-time', label: 'Part-Time', sub: 'Flexible hours', icon: '/images/categories/clay_icon_parttime.png' },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/contract', label: 'Contract', sub: 'Fixed-term roles', icon: '/images/categories/clay_icon_contract.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'part-time': {
    heroImage: '/images/categories/hero_wc_parttime.png',
    bgColor: '#c5bc77',
    bentoSectionLabel: 'Why Choose Part-Time',
    bentoImages: [
      '/images/categories/bento_pt_flex.png',
      '/images/categories/bento_pt_balance.png',
      '/images/categories/bento_pt_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_pt_clock.png',
      '/images/categories/icon_pt_income.png',
      '/images/categories/icon_pt_prn.png',
      '/images/categories/icon_pt_balance.png',
    ],
    exploreCards: [
      { href: '/jobs/full-time', label: 'Full-Time', sub: 'Standard schedules', icon: '/images/categories/clay_icon_fulltime.png' },
      { href: '/jobs/per-diem', label: 'Per Diem', sub: 'Daily assignments', icon: '/images/categories/clay_icon_perdiem.png' },
      { href: '/jobs/contract', label: 'Contract', sub: 'Fixed-term roles', icon: '/images/categories/clay_icon_contract.png' },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'contract': {
    heroImage: '/images/categories/hero_wc_contract.png',
    bgColor: '#adc2d7',
    bentoSectionLabel: 'Why Choose Contract',
    bentoImages: [
      '/images/categories/bento_ct_signing.png',
      '/images/categories/bento_ct_flexibility.png',
      '/images/categories/bento_ct_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_ct_terms.png',
      '/images/categories/icon_ct_rates.png',
      '/images/categories/icon_ct_settings.png',
      '/images/categories/icon_ct_convert.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/locum-tenens', label: 'Locum Tenens', sub: 'Travel assignments', icon: '/images/categories/clay_icon_locumtenens.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'entry-level': {
    heroImage: '/images/categories/hero_wc_entrylevel.png',
    bgColor: '#cbd9b8',
    bentoSectionLabel: 'Why Choose Entry Level',
    bentoImages: [
      '/images/categories/bento_el_mentorship.png',
      '/images/categories/bento_el_growth.png',
      '/images/categories/bento_el_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_el_mentorship.png',
      '/images/categories/icon_el_ramp.png',
      '/images/categories/icon_el_skills.png',
      '/images/categories/icon_el_cert.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'mid-career': {
    heroImage: '/images/categories/hero_wc_midcareer.png',
    bgColor: '#accfb9',
    bentoSectionLabel: 'Why Choose Mid-Career',
    bentoImages: [
      '/images/categories/bento_mc_lead.png',
      '/images/categories/bento_mc_specialize.png',
      '/images/categories/bento_mc_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_mc_salary.png',
      '/images/categories/icon_mc_leader.png',
      '/images/categories/icon_mc_niche.png',
      '/images/categories/icon_mc_teach.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'senior': {
    heroImage: '/images/categories/hero_wc_senior.png',
    bgColor: '#6a85a0',
    bentoSectionLabel: 'Why Choose Senior',
    bentoImages: [
      '/images/categories/bento_senior_leadership.png',
      '/images/categories/bento_senior_strategy.png',
      '/images/categories/bento_senior_compensation.png',
    ],
    bentoIcons: [
      '/images/categories/icon_senior_crown.png',
      '/images/categories/icon_senior_chart.png',
      '/images/categories/icon_senior_blueprint.png',
      '/images/categories/icon_senior_globe.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'hospital': {
    heroImage: '/images/categories/hero_wc_hospital.png',
    bgColor: '#a0c3d6',
    bentoSectionLabel: 'Why Choose Hospital',
    bentoImages: [
      '/images/categories/bento_ho_acute.png',
      '/images/categories/bento_ho_team.png',
      '/images/categories/bento_ho_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_ho_pay.png',
      '/images/categories/icon_ho_team.png',
      '/images/categories/icon_ho_acute.png',
      '/images/categories/icon_ho_loan.png',
    ],
    exploreCards: [
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'private-practice': {
    heroImage: '/images/categories/hero_wc_privatepractice.png',
    bgColor: '#d4b0a3',
    bentoSectionLabel: 'Why Choose Private Practice',
    bentoImages: [
      '/images/categories/bento_pp_office.png',
      '/images/categories/bento_pp_group.png',
      '/images/categories/bento_pp_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_pp_earning.png',
      '/images/categories/icon_pp_autonomy.png',
      '/images/categories/icon_pp_group.png',
      '/images/categories/icon_pp_hybrid.png',
    ],
    exploreCards: [
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'community-health': {
    heroImage: '/images/categories/hero_wc_communityhealth_v2.png',
    bgColor: '#5b7455',
    bentoSectionLabel: 'Why Choose Community Health',
    bentoImages: [
      '/images/categories/bento_ch_fqhc.png',
      '/images/categories/bento_ch_impact.png',
      '/images/categories/bento_ch_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_ch_grant.png',
      '/images/categories/icon_ch_heart.png',
      '/images/categories/icon_ch_diversity.png',
      '/images/categories/icon_ch_clinic.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'va': {
    heroImage: '/images/categories/hero_v2_va.png',
    bgColor: '#97b0c9',
    bentoSectionLabel: 'Why Choose VA & Government',
    bentoImages: [
      '/images/categories/bento_va_facility.png',
      '/images/categories/bento_va_care.png',
      '/images/categories/bento_va_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_va_flag.png',
      '/images/categories/icon_va_veteran.png',
      '/images/categories/icon_va_education.png',
      '/images/categories/icon_va_pension.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'geriatric': {
    heroImage: '/images/categories/hero_wc_geriatric.png',
    bgColor: '#d5c6e7',
    bentoSectionLabel: 'Why Choose Geriatric',
    bentoImages: [
      '/images/categories/bento_ge_memory.png',
      '/images/categories/bento_ge_snf.png',
      '/images/categories/bento_ge_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_ge_aging.png',
      '/images/categories/icon_ge_brain.png',
      '/images/categories/icon_ge_home.png',
      '/images/categories/icon_ge_pills.png',
    ],
    exploreCards: [
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'veterans': {
    heroImage: '/images/categories/hero_wc_veterans.png',
    bgColor: '#b8c8d4',
    bentoSectionLabel: 'Why Choose Veterans',
    bentoImages: [
      '/images/categories/bento_vet_ptsd.png',
      '/images/categories/bento_vet_support.png',
      '/images/categories/bento_vet_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_vet_mission.png',
      '/images/categories/icon_vet_training.png',
      '/images/categories/icon_vet_benefits.png',
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'lgbtq': {
    heroImage: '/images/categories/hero_wc_lgbtq.png',
    bgColor: '#e0c7a9',
    bentoSectionLabel: 'Why Choose LGBTQ+ Care',
    bentoImages: [
      '/images/categories/bento_lg_affirm.png',
      '/images/categories/bento_lg_inclusive.png',
      '/images/categories/bento_lg_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_lg_affirm.png',
      '/images/categories/icon_lg_gender.png',
      '/images/categories/icon_lg_safe.png',
      '/images/categories/icon_lg_impact.png',
    ],
    exploreCards: [
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
  'crisis': {
    heroImage: '/images/categories/hero_wc_crisis.png',
    bgColor: '#dbafac',
    bentoSectionLabel: 'Why Choose Crisis',
    bentoImages: [
      '/images/categories/bento_cr_intervention.png',
      '/images/categories/bento_cr_team.png',
      '/images/categories/bento_cr_salary.png',
    ],
    bentoIcons: [
      '/images/categories/icon_cr_demand.png',
      '/images/categories/icon_cr_lifesaving.png',
      '/images/categories/icon_cr_response.png',
      '/images/categories/icon_cr_team.png',
    ],
    exploreCards: [
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: '/images/categories/clay_icon_inpatient.png' },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: '/images/categories/clay_icon_remote.png' },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: '/images/categories/clay_icon_telehealth.png' },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: '/images/categories/clay_icon_outpatient.png' },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: '/images/categories/clay_icon_salary.png' },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: '/images/categories/clay_icon_location.png' },
    ],
  },
};
