// Auto-generated from category pages — Phase A of pSEO migration
// Maps each category slug to its visual assets for the pSEO template

import { siteAsset } from '@/lib/asset-url';

export interface ExploreCard { href: string; label: string; sub: string; icon: string; }

export interface CategoryAssets {
  heroImage: string;
  bgColor: string;
  bentoSectionLabel: string;
  bentoImages: string[];
  bentoIcons: string[];
  exploreCards: ExploreCard[];
}

export const CATEGORY_ASSET_REGISTRY: Record<string, CategoryAssets> = {
  'remote': {
    heroImage: siteAsset('images/categories/hero_wc_remote.webp'),
    bgColor: '#e8af9b',
    bentoSectionLabel: 'Why Go Remote',
    bentoImages: [
      siteAsset('images/categories/bento_remote_office.webp'),
      siteAsset('images/categories/bento_multi_state_impact.webp'),
      siteAsset('images/categories/bento_salary_growth.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_remote_flex.webp'),
      siteAsset('images/categories/icon_remote_home.webp'),
      siteAsset('images/categories/icon_remote_reach.webp'),
    ],
    exploreCards: [
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual patient care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/travel', label: 'Travel', sub: 'Locum tenens', icon: siteAsset('images/categories/clay_icon_travel.webp') },
      { href: '/jobs/new-grad', label: 'New Grad', sub: 'Entry-level roles', icon: siteAsset('images/categories/clay_icon_newgrad.webp') },
      { href: '/jobs/per-diem', label: 'Per Diem', sub: 'Flexible shifts', icon: siteAsset('images/categories/clay_icon_perdiem.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'telehealth': {
    heroImage: siteAsset('images/categories/hero_wc_th_people.webp'),
    bgColor: '#f1d49c',
    bentoSectionLabel: 'Why Choose Telehealth',
    bentoImages: [
      siteAsset('images/categories/bento_th_videocall.webp'),
      siteAsset('images/categories/bento_th_multistate.webp'),
      siteAsset('images/categories/bento_th_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_th_demand.webp'),
      siteAsset('images/categories/icon_th_access.webp'),
      siteAsset('images/categories/icon_telehealth_flex.webp'),
      siteAsset('images/categories/icon_telehealth_home.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/substance-abuse', label: 'Substance Abuse', sub: 'Addiction care', icon: siteAsset('images/categories/clay_icon_substance.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'inpatient': {
    heroImage: siteAsset('images/categories/hero_v3_inpatient.webp'),
    bgColor: '#a0b7c4',
    bentoSectionLabel: 'Why Choose Inpatient',
    bentoImages: [
      siteAsset('images/categories/bento_inp_ward.webp'),
      siteAsset('images/categories/bento_inp_comp.webp'),
      siteAsset('images/categories/bento_inpatient_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_inp_pay.webp'),
      siteAsset('images/categories/icon_inp_structured.webp'),
      siteAsset('images/categories/icon_inp_schedule.webp'),
    ],
    exploreCards: [
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based care', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/crisis', label: 'Crisis', sub: 'Emergency psych', icon: siteAsset('images/categories/clay_icon_crisis.webp') },
      { href: '/jobs/correctional', label: 'Correctional', sub: 'Forensic settings', icon: siteAsset('images/categories/clay_icon_correctional.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'outpatient': {
    heroImage: siteAsset('images/categories/hero_v2_outpatient.webp'),
    bgColor: '#9ed2ba',
    bentoSectionLabel: 'Why Choose Outpatient',
    bentoImages: [
      siteAsset('images/categories/bento_outpatient_clinic.webp'),
      siteAsset('images/categories/bento_outpatient_panel.webp'),
      siteAsset('images/categories/bento_outpatient_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_outpatient_clock.webp'),
      siteAsset('images/categories/icon_outpatient_therapy.webp'),
      siteAsset('images/categories/icon_outpatient_growth.webp'),
      siteAsset('images/categories/icon_outpatient_clinic.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/community-health', label: 'Community Health', sub: 'FQHC & public', icon: siteAsset('images/categories/clay_icon_communityhealth.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'travel': {
    heroImage: siteAsset('images/categories/hero_wc_travel.webp'),
    bgColor: '#81c1da',
    bentoSectionLabel: 'Why Choose Travel',
    bentoImages: [
      siteAsset('images/categories/bento_travel_adventure.webp'),
      siteAsset('images/categories/bento_travel_housing.webp'),
      siteAsset('images/categories/bento_travel_compensation.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_travel_dollar.webp'),
      siteAsset('images/categories/icon_travel_case.webp'),
      siteAsset('images/categories/icon_travel_plane.webp'),
      siteAsset('images/categories/icon_travel_housing.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/locum-tenens', label: 'Locum Tenens', sub: 'Short-term fills', icon: siteAsset('images/categories/clay_icon_locumtenens.webp') },
      { href: '/jobs/contract', label: 'Contract', sub: 'Fixed-term roles', icon: siteAsset('images/categories/clay_icon_contract.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'addiction': {
    heroImage: siteAsset('images/categories/hero_v2_addiction.webp'),
    bgColor: '#aabe9c',
    bentoSectionLabel: 'Why Choose Addiction & SUD',
    bentoImages: [
      siteAsset('images/categories/bento_addiction_recovery.webp'),
      siteAsset('images/categories/bento_addiction_mat.webp'),
      siteAsset('images/categories/bento_addiction_impact.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_addiction_demand.webp'),
      siteAsset('images/categories/icon_addiction_dual.webp'),
      siteAsset('images/categories/icon_addiction_harm.webp'),
      siteAsset('images/categories/icon_addiction_heart.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'child-adolescent': {
    heroImage: siteAsset('images/categories/hero_wc_childadolescent.webp'),
    bgColor: '#e3ac73',
    bentoSectionLabel: 'Why Choose Child & Adolescent',
    bentoImages: [
      siteAsset('images/categories/bento_child_clinic.webp'),
      siteAsset('images/categories/bento_child_school.webp'),
      siteAsset('images/categories/bento_child_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_child_teddy.webp'),
      siteAsset('images/categories/icon_child_school.webp'),
      siteAsset('images/categories/icon_child_family.webp'),
      siteAsset('images/categories/icon_child_play.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'substance-abuse': {
    heroImage: siteAsset('images/categories/hero_wc_sa_people.webp'),
    bgColor: '#9bb7a5',
    bentoSectionLabel: 'Why Choose Substance Abuse',
    bentoImages: [
      siteAsset('images/categories/bento_sa_counseling.webp'),
      siteAsset('images/categories/bento_sa_grouptherapy.webp'),
      siteAsset('images/categories/bento_sa_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_sa_recovery.webp'),
      siteAsset('images/categories/icon_sa_medicine.webp'),
      siteAsset('images/categories/icon_sa_group.webp'),
      siteAsset('images/categories/icon_sa_impact.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'new-grad': {
    heroImage: siteAsset('images/categories/hero_wc_newgrad.webp'),
    bgColor: '#99a7d4',
    bentoSectionLabel: 'Why Choose New Grad',
    bentoImages: [
      siteAsset('images/categories/bento_newgrad_mentorship.webp'),
      siteAsset('images/categories/bento_newgrad_career.webp'),
      siteAsset('images/categories/bento_newgrad_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_newgrad_bulb.webp'),
      siteAsset('images/categories/icon_newgrad_diploma.webp'),
      siteAsset('images/categories/icon_newgrad_stairs.webp'),
      siteAsset('images/categories/icon_newgrad_cert.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'per-diem': {
    heroImage: siteAsset('images/categories/hero_v2_perdiem.webp'),
    bgColor: '#dcba74',
    bentoSectionLabel: 'Why Choose Per Diem',
    bentoImages: [
      siteAsset('images/categories/bento_pd_shifts.webp'),
      siteAsset('images/categories/bento_pd_free.webp'),
      siteAsset('images/categories/bento_pd_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_perdiem_shift.webp'),
      siteAsset('images/categories/icon_perdiem_wallet.webp'),
      siteAsset('images/categories/icon_perdiem_nosign.webp'),
      siteAsset('images/categories/icon_perdiem_variety.webp'),
    ],
    exploreCards: [
      { href: '/jobs/part-time', label: 'Part-Time', sub: 'Flexible hours', icon: siteAsset('images/categories/clay_icon_parttime.webp') },
      { href: '/jobs/contract', label: 'Contract', sub: 'Fixed-term roles', icon: siteAsset('images/categories/clay_icon_contract.webp') },
      { href: '/jobs/locum-tenens', label: 'Locum Tenens', sub: 'Travel assignments', icon: siteAsset('images/categories/clay_icon_locumtenens.webp') },
      { href: '/jobs/full-time', label: 'Full-Time', sub: 'Standard schedules', icon: siteAsset('images/categories/clay_icon_fulltime.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'full-time': {
    heroImage: siteAsset('images/categories/hero_wc_fulltime.webp'),
    bgColor: '#88a7c4',
    bentoSectionLabel: 'Why Choose Full-Time',
    bentoImages: [
      siteAsset('images/categories/bento_ft_benefits.webp'),
      siteAsset('images/categories/bento_ft_stability.webp'),
      siteAsset('images/categories/bento_ft_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_ft_benefits.webp'),
      siteAsset('images/categories/icon_ft_security.webp'),
      siteAsset('images/categories/icon_ft_team.webp'),
      siteAsset('images/categories/icon_ft_balance.webp'),
    ],
    exploreCards: [
      { href: '/jobs/part-time', label: 'Part-Time', sub: 'Flexible hours', icon: siteAsset('images/categories/clay_icon_parttime.webp') },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/contract', label: 'Contract', sub: 'Fixed-term roles', icon: siteAsset('images/categories/clay_icon_contract.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'part-time': {
    heroImage: siteAsset('images/categories/hero_wc_parttime.webp'),
    bgColor: '#c5bc77',
    bentoSectionLabel: 'Why Choose Part-Time',
    bentoImages: [
      siteAsset('images/categories/bento_pt_flex.webp'),
      siteAsset('images/categories/bento_pt_balance.webp'),
      siteAsset('images/categories/bento_pt_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_pt_clock.webp'),
      siteAsset('images/categories/icon_pt_income.webp'),
      siteAsset('images/categories/icon_pt_prn.webp'),
      siteAsset('images/categories/icon_pt_balance.webp'),
    ],
    exploreCards: [
      { href: '/jobs/full-time', label: 'Full-Time', sub: 'Standard schedules', icon: siteAsset('images/categories/clay_icon_fulltime.webp') },
      { href: '/jobs/per-diem', label: 'Per Diem', sub: 'Daily assignments', icon: siteAsset('images/categories/clay_icon_perdiem.webp') },
      { href: '/jobs/contract', label: 'Contract', sub: 'Fixed-term roles', icon: siteAsset('images/categories/clay_icon_contract.webp') },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'contract': {
    heroImage: siteAsset('images/categories/hero_wc_contract.webp'),
    bgColor: '#adc2d7',
    bentoSectionLabel: 'Why Choose Contract',
    bentoImages: [
      siteAsset('images/categories/bento_ct_signing.webp'),
      siteAsset('images/categories/bento_ct_flexibility.webp'),
      siteAsset('images/categories/bento_ct_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_ct_rates.webp'),
      siteAsset('images/categories/icon_ct_convert.webp'),
      siteAsset('images/categories/icon_ct_terms.webp'),
      siteAsset('images/categories/icon_ct_settings.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/locum-tenens', label: 'Locum Tenens', sub: 'Travel assignments', icon: siteAsset('images/categories/clay_icon_locumtenens.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'entry-level': {
    heroImage: siteAsset('images/categories/hero_wc_entrylevel.webp'),
    bgColor: '#cbd9b8',
    bentoSectionLabel: 'Why Choose Entry Level',
    bentoImages: [
      siteAsset('images/categories/bento_el_mentorship.webp'),
      siteAsset('images/categories/bento_el_growth.webp'),
      siteAsset('images/categories/bento_el_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_el_mentorship.webp'),
      siteAsset('images/categories/icon_el_ramp.webp'),
      siteAsset('images/categories/icon_el_skills.webp'),
      siteAsset('images/categories/icon_el_cert.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'mid-career': {
    heroImage: siteAsset('images/categories/hero_wc_midcareer.webp'),
    bgColor: '#accfb9',
    bentoSectionLabel: 'Why Choose Mid-Career',
    bentoImages: [
      siteAsset('images/categories/bento_mc_lead.webp'),
      siteAsset('images/categories/bento_mc_specialize.webp'),
      siteAsset('images/categories/bento_mc_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_mc_salary.webp'),
      siteAsset('images/categories/icon_mc_leader.webp'),
      siteAsset('images/categories/icon_mc_niche.webp'),
      siteAsset('images/categories/icon_mc_teach.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'senior': {
    heroImage: siteAsset('images/categories/hero_wc_senior.webp'),
    bgColor: '#6a85a0',
    bentoSectionLabel: 'Why Choose Senior',
    bentoImages: [
      siteAsset('images/categories/bento_senior_leadership.webp'),
      siteAsset('images/categories/bento_senior_strategy.webp'),
      siteAsset('images/categories/bento_senior_compensation.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_senior_crown.webp'),
      siteAsset('images/categories/icon_senior_chart.webp'),
      siteAsset('images/categories/icon_senior_blueprint.webp'),
      siteAsset('images/categories/icon_senior_globe.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'hospital': {
    heroImage: siteAsset('images/categories/hero_wc_hospital.webp'),
    bgColor: '#a0c3d6',
    bentoSectionLabel: 'Why Choose Hospital',
    bentoImages: [
      siteAsset('images/categories/bento_ho_acute.webp'),
      siteAsset('images/categories/bento_ho_team.webp'),
      siteAsset('images/categories/bento_ho_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_ho_pay.webp'),
      siteAsset('images/categories/icon_ho_team.webp'),
      siteAsset('images/categories/icon_ho_loan.webp'),
      siteAsset('images/categories/icon_ho_acute.webp'),
    ],
    exploreCards: [
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'private-practice': {
    heroImage: siteAsset('images/categories/hero_wc_privatepractice.webp'),
    bgColor: '#d4b0a3',
    bentoSectionLabel: 'Why Choose Private Practice',
    bentoImages: [
      siteAsset('images/categories/bento_pp_office.webp'),
      siteAsset('images/categories/bento_pp_group.webp'),
      siteAsset('images/categories/bento_pp_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_pp_earning.webp'),
      siteAsset('images/categories/icon_pp_autonomy.webp'),
      siteAsset('images/categories/icon_pp_group.webp'),
      siteAsset('images/categories/icon_pp_hybrid.webp'),
    ],
    exploreCards: [
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'community-health': {
    heroImage: siteAsset('images/categories/hero_wc_communityhealth_v2.webp'),
    bgColor: '#5b7455',
    bentoSectionLabel: 'Why Choose Community Health',
    bentoImages: [
      siteAsset('images/categories/bento_ch_fqhc.webp'),
      siteAsset('images/categories/bento_ch_impact.webp'),
      siteAsset('images/categories/bento_ch_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_ch_grant.webp'),
      siteAsset('images/categories/icon_ch_heart.webp'),
      siteAsset('images/categories/icon_ch_diversity.webp'),
      siteAsset('images/categories/icon_ch_clinic.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'va': {
    heroImage: siteAsset('images/categories/hero_v2_va.webp'),
    bgColor: '#97b0c9',
    bentoSectionLabel: 'Why Choose VA & Government',
    bentoImages: [
      siteAsset('images/categories/bento_va_facility.webp'),
      siteAsset('images/categories/bento_va_care.webp'),
      siteAsset('images/categories/bento_va_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_va_flag.webp'),
      siteAsset('images/categories/icon_va_veteran.webp'),
      siteAsset('images/categories/icon_va_education.webp'),
      siteAsset('images/categories/icon_va_pension.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'geriatric': {
    heroImage: siteAsset('images/categories/hero_wc_geriatric.webp'),
    bgColor: '#d5c6e7',
    bentoSectionLabel: 'Why Choose Geriatric',
    bentoImages: [
      siteAsset('images/categories/bento_ge_memory.webp'),
      siteAsset('images/categories/bento_ge_snf.webp'),
      siteAsset('images/categories/bento_ge_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_ge_aging.webp'),
      siteAsset('images/categories/icon_ge_brain.webp'),
      siteAsset('images/categories/icon_ge_pills.webp'),
      siteAsset('images/categories/icon_ge_home.webp'),
    ],
    exploreCards: [
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'veterans': {
    heroImage: siteAsset('images/categories/hero_wc_veterans.webp'),
    bgColor: '#b8c8d4',
    bentoSectionLabel: 'Why Choose Veterans',
    bentoImages: [
      siteAsset('images/categories/bento_vet_ptsd.webp'),
      siteAsset('images/categories/bento_vet_support.webp'),
      siteAsset('images/categories/bento_vet_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_vet_mission.webp'),
      siteAsset('images/categories/icon_vet_training.webp'),
      siteAsset('images/categories/icon_vet_benefits.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'lgbtq': {
    heroImage: siteAsset('images/categories/hero_wc_lgbtq.webp'),
    bgColor: '#e0c7a9',
    bentoSectionLabel: 'Why Choose LGBTQ+ Care',
    bentoImages: [
      siteAsset('images/categories/bento_lg_affirm.webp'),
      siteAsset('images/categories/bento_lg_inclusive.webp'),
      siteAsset('images/categories/bento_lg_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_lg_affirm.webp'),
      siteAsset('images/categories/icon_lg_gender.webp'),
      siteAsset('images/categories/icon_lg_impact.webp'),
      siteAsset('images/categories/icon_lg_safe.webp'),
    ],
    exploreCards: [
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'crisis': {
    heroImage: siteAsset('images/categories/hero_wc_crisis.webp'),
    bgColor: '#dbafac',
    bentoSectionLabel: 'Why Choose Crisis',
    bentoImages: [
      siteAsset('images/categories/bento_cr_intervention.webp'),
      siteAsset('images/categories/bento_cr_team.webp'),
      siteAsset('images/categories/bento_cr_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_cr_demand.webp'),
      siteAsset('images/categories/icon_cr_lifesaving.webp'),
      siteAsset('images/categories/icon_cr_response.webp'),
      siteAsset('images/categories/icon_cr_team.webp'),
    ],
    exploreCards: [
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: '50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  '1099': {
    heroImage: siteAsset('images/categories/hero_wc_1099.webp'),
    bgColor: '#d19b99',
    bentoSectionLabel: 'Why Choose 1099',
    bentoImages: [
      siteAsset('images/categories/bento_1099_freedom.webp'),
      siteAsset('images/categories/bento_1099_tax.webp'),
      siteAsset('images/categories/bento_1099_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_1099_autonomy.webp'),
      siteAsset('images/categories/icon_1099_schedule.webp'),
      siteAsset('images/categories/icon_1099_multi.webp'),
    ],
    exploreCards: [
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/jobs/locum-tenens', label: 'Locum Tenens', sub: 'Travel assignments', icon: siteAsset('images/categories/clay_icon_locumtenens.webp') },
      { href: '/jobs/per-diem', label: 'Per Diem', sub: 'Flexible shifts', icon: siteAsset('images/categories/clay_icon_perdiem.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'behavioral-health': {
    heroImage: siteAsset('images/categories/hero_wc_behavioralhealth.webp'),
    bgColor: '#a8c4d4',
    bentoSectionLabel: 'Why Choose Behavioral Health',
    bentoImages: [
      siteAsset('images/categories/bento_bh_team.webp'),
      siteAsset('images/categories/bento_bh_facility.webp'),
      siteAsset('images/categories/bento_bh_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_bh_team.webp'),
      siteAsset('images/categories/icon_bh_growth.webp'),
      siteAsset('images/categories/icon_bh_building.webp'),
    ],
    exploreCards: [
      { href: '/jobs/outpatient', label: 'Outpatient', sub: 'Clinic-based', icon: siteAsset('images/categories/clay_icon_outpatient.webp') },
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/community-health', label: 'Community Health', sub: 'FQHC & public', icon: siteAsset('images/categories/clay_icon_community.webp') },
      { href: '/jobs/telehealth', label: 'Telehealth', sub: 'Virtual care', icon: siteAsset('images/categories/clay_icon_telehealth.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'correctional': {
    heroImage: siteAsset('images/categories/hero_wc_correctional.webp'),
    bgColor: '#8e9baa',
    bentoSectionLabel: 'Why Choose Correctional',
    bentoImages: [
      siteAsset('images/categories/bento_corr_facility.webp'),
      siteAsset('images/categories/bento_corr_salary.webp'),
      siteAsset('images/categories/bento_corr_skills.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_corr_pay.webp'),
      siteAsset('images/categories/icon_corr_loan.webp'),
      siteAsset('images/categories/icon_corr_forensic.webp'),
    ],
    exploreCards: [
      { href: '/jobs/inpatient', label: 'Inpatient', sub: 'Hospital roles', icon: siteAsset('images/categories/clay_icon_inpatient.webp') },
      { href: '/jobs/crisis', label: 'Crisis', sub: 'Emergency psych', icon: siteAsset('images/categories/clay_icon_crisis.webp') },
      { href: '/jobs/va', label: 'VA', sub: 'Federal roles', icon: siteAsset('images/categories/clay_icon_va.webp') },
      { href: '/jobs/veterans', label: 'Veterans', sub: 'Military mental health', icon: siteAsset('images/categories/clay_icon_veterans.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
  'locum-tenens': {
    heroImage: siteAsset('images/categories/hero_wc_locumtenens.webp'),
    bgColor: '#c4a882',
    bentoSectionLabel: 'Why Choose Locum Tenens',
    bentoImages: [
      siteAsset('images/categories/bento_locum_travel.webp'),
      siteAsset('images/categories/bento_locum_pay.webp'),
      siteAsset('images/categories/bento_locum_salary.webp'),
    ],
    bentoIcons: [
      siteAsset('images/categories/icon_locum_rates.webp'),
      siteAsset('images/categories/icon_locum_calendar.webp'),
      siteAsset('images/categories/icon_locum_map.webp'),
    ],
    exploreCards: [
      { href: '/jobs/travel', label: 'Travel', sub: 'Travel assignments', icon: siteAsset('images/categories/clay_icon_travel.webp') },
      { href: '/jobs/1099', label: '1099', sub: 'Independent contractor', icon: siteAsset('images/categories/clay_icon_1099.webp') },
      { href: '/jobs/remote', label: 'Remote', sub: 'Work from home', icon: siteAsset('images/categories/clay_icon_remote.webp') },
      { href: '/jobs/contract', label: 'Contract', sub: 'Temp-to-perm', icon: siteAsset('images/categories/clay_icon_contract.webp') },
      { href: '/salary-guide', label: 'Salary Guide', sub: '2026 comp data', icon: siteAsset('images/categories/clay_icon_salary.webp') },
      { href: '/jobs/locations', label: 'By Location', sub: 'All 50 states', icon: siteAsset('images/categories/clay_icon_location.webp') },
    ],
  },
};
