-- Phase 1 Sprint 1.2 — daily personalized job recommendations.
--
-- One row per (candidate, job) pair generated by the daily cron. Each batch
-- has a `batch_id` so the UI shows only the latest run; older batches stay
-- around for click-through analytics + A/B test attribution.
--
-- The cron also tracks engagement: `clicked_at` is set the first time the
-- candidate clicks through from the recommendation surface. Used as a
-- training signal once we add a click-feedback rerank model.

CREATE TABLE IF NOT EXISTS "candidate_recommendations" (
    "id"            TEXT          NOT NULL,
    "supabase_id"   TEXT          NOT NULL,                              -- candidate
    "job_id"        TEXT          NOT NULL,
    "batch_id"      TEXT          NOT NULL,                              -- groups one cron run; UI filters latest
    "rank"          INTEGER       NOT NULL,                              -- 1..N within the batch
    "similarity"    DOUBLE PRECISION NOT NULL,                           -- cosine similarity 0..1
    "reason"        TEXT,                                                -- short explanation (optional, populated from LLM rerank)
    "clicked_at"    TIMESTAMP(3),
    "dismissed_at"  TIMESTAMP(3),
    "created_at"    TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "candidate_recommendations_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "candidate_recommendations_job_fkey" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE
);

-- Latest-batch lookup is the hot path.
CREATE INDEX IF NOT EXISTS "candidate_recommendations_supabase_batch_idx"
    ON "candidate_recommendations" ("supabase_id", "batch_id", "rank");
-- Click analytics + dedupe: never recommend a job to a candidate twice across batches in a 30-day window.
CREATE INDEX IF NOT EXISTS "candidate_recommendations_supabase_job_idx"
    ON "candidate_recommendations" ("supabase_id", "job_id", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "candidate_recommendations_clicked_idx"
    ON "candidate_recommendations" ("clicked_at" DESC) WHERE "clicked_at" IS NOT NULL;
